language: C

sudo: required

os:
  - linux

services:
  - docker

script:
  - ./script/build-release.sh
  
deploy:
  skip_cleanup: true
  on:
    tags: true
  provider: script
  script: bash script/publish.sh
