language: C

sudo: required

os:
  - linux

before_deploy: ""

services:
  - docker

script:
  - ./script/build-release.sh myapp ${TRAVIS_TAG}-${TRAVIS_OS_NAME}
  - strip gpm
  - git clone https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/aerys/gpm-packages.git
