language: C

sudo: required

os:
  - linux

services:
  - docker

script:
  - ./script/build-release.sh gpm
  
deploy:
  skip_cleanup: true
  on:
    branch: feature/travis-ci
  provider: script
  script: bash script/publish.sh
