[package]
name = "gpm"
version = "0.12.0"
authors = ["Jean-Marc Le Roux <jeanmarc.leroux@aerys.in>"]
edition = "2018"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
incremental = false
# We cannot use both lto = true and opt-level = "z" because of this bug:
# https://github.com/mitsuhiko/indicatif/issues/88
opt-level = "s"

[dependencies.gitlfs]
path = "./gitlfs"

[dependencies]
clap = "2.33.0"
tempfile = "3.1.0"
log = "0.4.8"
pretty_env_logger = "0.3.1"
git2 = "0.11.0"
url = "2.1.1"
ssh2 = "0.6.0"
json = "0.12.0"
reqwest = "0.10.1"
tar = "0.4.26"
flate2 = "1.0.13"
rpassword = "4.0.3"
pest = "2.1.2"
pest_derive = "2.1.0"
regex = "1.3.3"
indicatif = "0.13.0"
console = "0.9.1"
crypto-hash = "0.3.4"
dirs = "2.0.2"
semver = "0.9.0"
dotenv = "0.15.0"
err-derive = "0.2.3"
