[package]
name = "gpm"
version = "0.10.1"
authors = ["Jean-Marc Le Roux <jeanmarc.leroux@aerys.in>"]
edition = "2018"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
incremental = false
opt-level = "z"

[dependencies.gitlfs]
path = "./gitlfs"

[dependencies]
clap = "2.32.0"
tempfile = "3"
log = "0.4.3"
pretty_env_logger = "0.2.3"
git2 = "0.7.5"
url = "1.7.1"
ssh2 = "0.3"
json = "0.11.13"
reqwest = "0.8.6"
tar = "0.4.16"
flate2 = "1.0.1"
rpassword = "2.0.0"
pest = "1.0.6"
pest_derive = "1.0.7"
regex = "1"
indicatif = "0.9.0"
console = "0.6.1"
crypto-hash = "0.3.1"
dirs = "1.0.4"
